version: '3.8'

# Services
services:

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: septcera4183
      MYSQL_DATABASE: septcera_mysql
      MYSQL_USER: septcera
      MYSQL_PASSWORD: septcera4183
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql 

  php:
    container_name: php
    build:
      context: .
      dockerfile: ./php/dockerfile
      args:
          BUILD_COMPOSER_AUTH: ${DEVELOPER_COMPOSER_AUTH}
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/septcera_docker
    depends_on:
      - database
      
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/septcera_docker
    depends_on:
      - php
      - database
    

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:8080' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      