version: '3.8'

# Services
services:

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: septcera4183
      MYSQL_DATABASE: septcera_mysql
      MYSQL_USER: septcera
      MYSQL_PASSWORD: septcera4183
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql 

  php:
    container_name: php
    build:
      context: .
      dockerfile: ./php/dockerfile
      args:
          BUILD_COMPOSER_AUTH: ${DEVELOPER_COMPOSER_AUTH}
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/septcera_docker
    depends_on:
      - database
      
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '50000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/septcera_docker
    depends_on:
      - php
      - database
    