kernel:
    resource: ../src/Kernel.php
    type: annotation

health_check:
    path: /
    methods: [GET]
    defaults: {_controller: 'App\Infrastructure\Action\HealthCheck' }

# User
create_user:
    path: /user
    methods: [POST]
    controller: App\Infrastructure\Action\User\Create

# chat
create_chat:
    path: /chat
    methods: [POST]
    controller: App\Infrastructure\Action\Chat\Create
