kernel:
    resource: ../src/Kernel.php
    type: annotation

# User
create_user:
    path: /user
    methods: [POST]
    controller: App\Infrastructure\Action\User\Create

GetById:
    path: /user/{id}
    methods: [GET]
    controller: App\Infrastructure\Action\User\GetById

# chat
create_chat:
    path: /chat
    methods: [POST]
    controller: App\Infrastructure\Action\Chat\Create

# chat user
add_user_to_chat:
    path: /chat_user
    methods: [POST]
    controller: App\Infrastructure\Action\ChatUser\Create

# chat bericht
create_user_chat_bericht:
    path: /chat_bericht
    methods: [POST]
    controller: App\Infrastructure\Action\ChatBericht\Create

get_chat_message_by_chat_id:
    path: /chatBericht/{id}
    methods: [GET]
    controller: App\Infrastructure\Action\ChatBericht\GetByChatId

get_chat_message_by_user_id:
    path: /chat_bericht/user/{user_id}
    methods: [GET]
    controller: App\Infrastructure\Action\ChatBericht\GetByUser

#village
createVillage:
    path: /village
    methods: [POST]
    controller: App\Infrastructure\Action\Village\Create

specificVillage:
    path: /village/{parameters}
    methods: [GET]
    controller: App\Infrastructure\Action\Village\GetSpecific

ownVillage:
    path: /ownVillages
    methods: [GET]
    controller: App\Infrastructure\Action\Village\GetOwn


#views
loginView:
    path: /login
    methods: [GET]
    controller: App\View\Account\LoginView

registerView:
    path: /register
    methods: [GET]
    controller: App\View\Account\Register

ForgotPassword:
    path: /ForgotPassword
    methods: [GET]
    controller: App\View\Account\ForgotPassword

villageView:
    path: /villageView
    methods: [GET]
    controller: App\View\Screens\VillageView

testView:
    path: /test
    methods: [GET]
    controller: App\View\TestViesdfw

testView2:
    path: /test2
    methods: [GET]
    controller: App\View\Test2

#general
basic:
    path: /
    controller: App\View\Account\LoginView
test:
    path: /test
    controller: App\View\TestViesdfw
