kernel:
    resource: ../src/Kernel.php
    type: annotation

health_check:
    path: /
    methods: [GET]
    defaults: {_controller: 'App\Infrastructure\Action\HealthCheck' }

# User
create_user:
    path: /user
    methods: [POST]
    controller: App\Infrastructure\Action\User\Create

# chat
create_chat:
    path: /chat
    methods: [POST]
    controller: App\Infrastructure\Action\Chat\Create

# chat user
add_user_to_chat:
    path: /chat_user
    methods: [POST]
    controller: App\Infrastructure\Action\ChatUser\Create

# chat bericht
user_chat_bericht:
    path: /chat_bericht
    methods: [POST]
    controller: App\Infrastructure\Action\ChatBericht\Create

get_chat_message_by_user_id:
    path: /chat_bericht/user/{user_id}
    methods: [GET]
    controller: App\Infrastructure\Action\ChatBericht\GetByUser

#village
createVillage:
    path: /village
    methods: [POST]
    controller: App\Infrastructure\Action\Village\Create

specificVillage:
    path: /village
    methods: [GET]
    controller: App\Infrastructure\Action\Village\GetSpecific

loginView:
    path: /login
    methods: [GET]
    controller: App\View\Login\LoginView
