createUnit:
    path: /unit
    methods: [POST]
    controller: App\Infrastructure\Action\Unit\Create

updateUnit:
    path: /updateUnit
    methods: [POST]
    controller: App\Infrastructure\Action\Unit\Update

deleteUnit:
    path: /deleteUnit
    methods: [POST]
    controller: App\Infrastructure\Action\Unit\Delete

GetUnitById:
    path: /unit
    methods: [GET]
    controller: App\Infrastructure\Action\Unit\GetById

GetUnitByParams:
    path: /unit/general
    methods: [GET]
    controller: App\Infrastructure\Action\Unit\GetByParams